### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Serg4y** [sulsoltanoff/gpt-integrate-telegram#1]
такая ошибка в строке ALLOWED_USERS = os.getenv("ALLOWED_USERS").split(",")

**Comment by sulsoltanoff** [comment]
Ошибка 'NoneType' object has no attribute 'split' возникает, когда вы пытаетесь вызвать метод split() на переменной, которая имеет значение None.

Добавил проверку на NoneType. 

Спасибо.
